apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tasco-growth
resources:
  - 00-namespace.yaml
  - 10-configmap.yaml
  - 15-external-secret.yaml
  - 20-deployment.yaml
  - 30-service-ingress.yaml
  - 40-hpa-pdb.yaml
  - 50-networkpolicy.yaml
  - 60-jobs.yaml
images:
  - name: REGISTRY/tasco-growth-platform
    newName: ghcr.io/iortatexhnxt-dev/tasco-growth-platform
    newTag: IMAGE_TAG
