'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { makeContainer, startServer, findProfile } = require('../helpers');

let c;
let srv;
test.before(async () => { c = await makeContainer(); srv = await startServer(c); });
test.after(async () => { await srv.close(); });

test('health, readiness, metrics, OpenAPI and static assets', async () => {
  assert.equal((await srv.call('GET', '/health/live')).status, 200);
  const ready = await srv.call('GET', '/health/ready');
  assert.equal(ready.status, 200);
  assert.equal(ready.body.status, 'ready');
  const spec = await srv.call('GET', '/api/openapi.json');
  assert.equal(spec.body.openapi, '3.1.0');
  assert.ok(Object.keys(spec.body.paths).length > 50);
  assert.equal(spec.body.paths['/api/customer/orders'].post.parameters.find((p) => p.name === 'Idempotency-Key').required, true);
  assert.equal(spec.body.paths['/api/orders'], undefined, 'no staff payment endpoint');
  const html = await srv.call('GET', '/');
  assert.equal(html.status, 200);
  assert.match(html.headers.get('content-type'), /text\/html/);
  assert.match(html.headers.get('content-security-policy'), /default-src 'self'/);
  assert.equal(html.headers.get('x-frame-options'), 'DENY');
  assert.equal((await srv.call('GET', '/app/')).status, 200);
  assert.equal((await srv.call('GET', '/verify/TAS-X')).status, 200);
  assert.equal((await srv.call('GET', '/vendor/qrcode.mjs')).headers.get('content-type'), 'text/javascript; charset=utf-8');
  assert.equal((await srv.call('GET', '/nope.html')).status, 404);
  const metrics = await srv.call('GET', '/metrics');
  assert.match(metrics.body, /http_requests_total/);
  const meta = await srv.call('GET', '/api/meta');
  assert.equal(meta.body.demoMode, true);
  assert.ok(meta.body.demoCustomers.length > 0);
});

test('authentication and authorisation (401/403) and error envelope', async () => {
  const unauth = await srv.call('GET', '/api/leads');
  assert.equal(unauth.status, 401);
  assert.equal(unauth.body.error.code, 'UNAUTHENTICATED');
  assert.ok(unauth.body.error.requestId);
  const agent = await srv.login('agent.hn');
  const forbidden = await srv.call('GET', '/api/users', { token: agent });
  assert.equal(forbidden.status, 403);
  const me = await srv.call('GET', '/api/auth/me', { token: agent });
  assert.equal(me.body.region, 'Hà Nội');
  assert.equal((await srv.call('GET', '/api/nope', { token: agent })).status, 404);
  assert.equal((await srv.call('DELETE', '/api/leads', { token: agent })).status, 405);
  const bad = await srv.call('POST', '/api/auth/login', { body: { username: 'x', password: 'y', extra: 1 } });
  assert.equal(bad.status, 400);
  assert.ok(bad.body.error.details.includes('extra is not allowed'));
  const out = await srv.call('POST', '/api/auth/logout', { token: agent });
  assert.equal(out.status, 200);
  assert.equal((await srv.call('GET', '/api/auth/me', { token: agent })).status, 401);
});

test('MFA login over HTTP and demo TOTP helper', async () => {
  const r = await srv.call('POST', '/api/auth/login', { body: { username: 'compliance', password: 'Tasco@Demo2026!' } });
  assert.equal(r.body.mfaRequired, true);
  const code = await srv.call('GET', '/api/demo/totp/compliance');
  const m = await srv.call('POST', '/api/auth/mfa', { body: { mfaToken: r.body.mfaToken, code: code.body.code } });
  assert.ok(m.body.accessToken);
  assert.equal((await srv.call('GET', '/api/demo/totp/nobody')).status, 404);
});

test('campaign manager journey: dashboard, leads, customer 360 (masked), journeys, events, voice campaign', async () => {
  const t = await srv.login('campaign');
  const ov = await srv.call('GET', '/api/dashboard/overview', { token: t });
  assert.ok(ov.body.base.profiles > 300);
  assert.equal((await srv.call('GET', '/api/dashboard/adoption', { token: t })).status, 200);
  const leads = await srv.call('GET', '/api/leads?tier=hot&limit=5&sort=score', { token: t });
  assert.equal(leads.status, 200);
  assert.equal((await srv.call('GET', '/api/leads?tier=boiling', { token: t })).status, 400);
  const p = await findProfile(c, (x) => x.phone && x.name);
  const d = await srv.call('GET', `/api/customers/${p.id}`, { token: t });
  assert.equal(d.status, 200);
  assert.equal(d.body.profile.piiMasked, true, 'campaign manager sees masked PII');
  assert.notEqual(d.body.profile.phone, p.phone);
  assert.equal((await srv.call('GET', `/api/customers/${p.id}/lineage`, { token: t })).status, 200);
  assert.equal((await srv.call('GET', '/api/touchpoints?status=scheduled&limit=5', { token: t })).status, 200);
  const run = await srv.call('POST', '/api/journeys/run', { token: t, body: { date: '2026-10-07', at: '2026-10-07T03:00:00Z' } });
  assert.ok(run.body.due >= 0);
  const ev = await srv.call('POST', '/api/ecosystem/events', { token: t, body: { type: 'vetc.inspection_booked', profileId: p.id } });
  assert.equal(ev.status, 200);
  const camp = await srv.call('POST', '/api/voice/campaign', { token: t, body: { limit: 3, at: '2026-10-07T03:00:00Z' } });
  assert.equal(camp.status, 200);
  assert.ok(camp.body.called <= 3);
  const night = await srv.call('POST', '/api/voice/campaign', { token: t, body: { limit: 3, at: '2026-10-07T15:00:00Z' } });
  assert.equal(night.body.called, 0, 'no marketing calls at 22:00 local');
  assert.ok(night.body.skipped['outside allowed contact hours'] > 0);
  assert.equal((await srv.call('POST', '/api/leads/recompute', { token: t })).status, 200);
  assert.equal((await srv.call('GET', '/api/rules', { token: t })).status, 200);
  assert.equal((await srv.call('POST', '/api/rules', { token: t, body: { kind: 'scoring', payload: {} } })).status, 403, 'campaign manager cannot author rules');
});

test('telesales agent: voice console → handoff → claim → quote → issue (idempotent)', async () => {
  const t = await srv.login('agent.hn');
  const p = await findProfile(c, (x) => x.province === 'Hà Nội' && x.consent.call && !x.consent.dnc && x.phone && x.ownerType === 'individual' && x.policy.insurer !== 'TASCO');
  const s = await srv.call('POST', '/api/voice/sessions', { token: t, body: { profileId: p.id } });
  assert.equal(s.status, 200);
  await srv.call('POST', `/api/voice/sessions/${s.body.id}/turns`, { token: t, body: { text: p.plate.replace('-', ' ').replace('.', ' ') } });
  await srv.call('POST', `/api/voice/sessions/${s.body.id}/turns`, { token: t, body: { text: 'đúng' } });
  const end = await srv.call('POST', `/api/voice/sessions/${s.body.id}/turns`, { token: t, body: { text: 'mua ngay' } });
  assert.equal(end.body.outcome, 'hot_handoff');
  assert.equal((await srv.call('GET', `/api/voice/sessions/${s.body.id}`, { token: t })).status, 200);
  const inbox = await srv.call('GET', '/api/handoffs?status=open', { token: t });
  assert.ok(inbox.body.items.some((h) => h.id === end.body.handoffId));
  assert.ok(inbox.body.items.every((h) => h.region === 'Hà Nội'), 'regional ABAC');
  const ho = await srv.call('GET', `/api/handoffs/${end.body.handoffId}`, { token: t });
  const claim = await srv.call('PATCH', `/api/handoffs/${ho.body.id}`, { token: t, body: { status: 'claimed', version: ho.body.version } });
  assert.equal(claim.body.assignedTo, ho.body.assignedTo ?? claim.body.assignedTo);
  assert.equal((await srv.call('PATCH', `/api/handoffs/${ho.body.id}`, { token: t, body: { assignTo: 'someone' } })).status, 403, 'only supervisors assign');
  const mine = await srv.call('GET', '/api/handoffs?status=claimed&mine=true', { token: t });
  assert.equal(mine.body.items.length, 1);
  const detail = await srv.call('GET', `/api/customers/${p.id}`, { token: t });
  assert.equal(detail.body.profile.phone, p.phone, 'agent may see PII for the call');
  assert.equal((await srv.call('GET', '/api/products', { token: t })).status, 200);
  const q = await srv.call('POST', '/api/quotes', { token: t, body: { profileId: p.id, products: [{ code: 'TNDS_CAR' }], channel: 'telesales' } });
  assert.equal(q.status, 200);
  assert.equal((await srv.call('POST', '/api/orders', { token: t, body: { quoteId: q.body.id } })).status, 404, 'staff cannot take payment');
  const sent = await srv.call('POST', `/api/quotes/${encodeURIComponent(q.body.id)}/send`, { token: t });
  assert.equal(sent.status, 200);
  const ct = (await srv.call('POST', '/api/customer/session', { body: { link: c.links.sign(p.id) } })).body.token;
  const pending = await srv.call('GET', '/api/customer/quotes', { token: ct });
  assert.ok(pending.body.some((x) => x.id === q.body.id), 'customer sees the quote in the app');
  const noKey = await srv.call('POST', '/api/customer/orders', { token: ct, body: { quoteId: q.body.id } });
  assert.equal(noKey.status, 400);
  const o1 = await srv.call('POST', '/api/customer/orders', { token: ct, body: { quoteId: q.body.id }, headers: { 'Idempotency-Key': 'api-test-0001' } });
  assert.equal(o1.status, 200);
  const o2 = await srv.call('POST', '/api/customer/orders', { token: ct, body: { quoteId: q.body.id }, headers: { 'Idempotency-Key': 'api-test-0001' } });
  assert.equal(o2.body.idempotentReplay, true);
  assert.equal(o2.body.order.id, o1.body.order.id);
  const cert = await srv.call('GET', `/api/public/certificates/${encodeURIComponent(o1.body.policies[0].certNo)}`);
  assert.equal(cert.body.issued, true);
  assert.ok(['in_force', 'not_yet_in_force'].includes(cert.body.state), 'renewal starts when current cover ends');
  assert.equal((await srv.call('GET', `/api/policies?profileId=${p.id}`, { token: t })).body.length, 1);
  const won = await srv.call('PATCH', `/api/handoffs/${ho.body.id}`, { token: t, body: { status: 'won', note: 'sold TNDS' } });
  assert.equal(won.body.status, 'won');
  const outside = await findProfile(c, (x) => x.province !== 'Hà Nội');
  assert.equal((await srv.call('GET', `/api/customers/${outside.id}`, { token: t })).status, 403, 'region outside ABAC scope');
});

test('rule author + approver maker-checker over HTTP, with simulation', async () => {
  const author = await srv.login('author');
  const approver = await srv.login('approver');
  const active = (await srv.call('GET', '/api/rules?kind=nba&status=active', { token: author })).body[0];
  const full = await srv.call('GET', `/api/rules/${encodeURIComponent(active.id)}`, { token: author });
  const payload = full.body.payload;
  payload.rules[0].then.label = 'Do not contact (customer opted out)';
  const val = await srv.call('POST', '/api/rules/validate', { token: author, body: { kind: 'nba', payload } });
  assert.deepEqual(val.body.errors, []);
  const p = await findProfile(c, () => true);
  const sim = await srv.call('POST', '/api/rules/simulate', { token: author, body: { profileId: p.id, kind: 'nba', payload } });
  assert.ok(sim.body.current && sim.body.candidate);
  assert.equal((await srv.call('POST', '/api/rules/simulate', { token: author, body: { profileId: 'NOPE', kind: 'nba', payload } })).status, 404);
  assert.equal((await srv.call('POST', '/api/rules/simulate', { token: author, body: { profileId: p.id, kind: 'nba', payload: { rules: 'x' } } })).status, 400);
  const draft = await srv.call('POST', '/api/rules', { token: author, body: { kind: 'nba', payload, description: 'label tweak' } });
  assert.equal(draft.status, 200);
  assert.equal((await srv.call('POST', `/api/rules/${encodeURIComponent(draft.body.id)}/submit`, { token: author, body: {} })).status, 200);
  assert.equal((await srv.call('POST', `/api/rules/${encodeURIComponent(draft.body.id)}/approve`, { token: author, body: {} })).status, 403);
  const ok = await srv.call('POST', `/api/rules/${encodeURIComponent(draft.body.id)}/approve`, { token: approver, body: { comment: 'LGTM' } });
  assert.equal(ok.body.status, 'active');
  assert.equal((await srv.call('GET', '/api/audit/verify', { token: approver })).body.ok, true);
  assert.equal((await srv.call('GET', '/api/dashboard/governance', { token: approver })).status, 200);
  assert.ok((await srv.call('GET', '/api/audit?action=rules.approved', { token: approver })).body.length >= 1);
});

test('partner API: API key auth, new-vehicle onboarding, bind, own policies, statement, IDOR protection', async () => {
  const pm = await srv.login('partners');
  assert.equal((await srv.call('GET', '/api/partners', { token: pm })).status, 200);
  const created = await srv.call('POST', '/api/partners', { token: pm, body: { name: 'Showroom 2', type: 'showroom' } });
  const key = (await srv.call('POST', `/api/partners/${created.body.id}/keys`, { token: pm })).body.apiKey;
  const other = (await srv.call('POST', '/api/partners/P-AGENT-01/keys', { token: pm })).body.apiKey;
  assert.equal((await srv.call('POST', '/api/partner/v1/quotes', { body: { plate: '30K-111.22', products: [{ code: 'TNDS_CAR' }] } })).status, 401);
  assert.equal((await srv.call('POST', '/api/partner/v1/quotes', { headers: { 'X-Api-Key': key }, body: { plate: 'bad', products: [{ code: 'TNDS_CAR' }] } })).status, 400);
  assert.equal((await srv.call('POST', '/api/partner/v1/quotes', { headers: { 'X-Api-Key': key }, body: { plate: '30K-111.22', phone: '123', products: [{ code: 'TNDS_CAR' }] } })).status, 400);
  const q = await srv.call('POST', '/api/partner/v1/quotes', { headers: { 'X-Api-Key': key }, body: { plate: '30K-111.22', holderName: 'Trần Mới', phone: '0912888999', seats: 7, usage: 'personal', products: [{ code: 'TNDS_CAR' }, { code: 'PA_SEAT', options: { sumInsuredPerSeat: 10000000 } }] } });
  assert.equal(q.status, 200);
  assert.equal(q.body.lines[0].total, 873400, '6–11 seat tariff incl. VAT');
  const idor = await srv.call('POST', '/api/partner/v1/orders', { headers: { 'X-Api-Key': other, 'Idempotency-Key': 'idor-test-01' }, body: { quoteId: q.body.id } });
  assert.equal(idor.status, 404, 'a partner cannot bind another partner\'s quote');
  const o = await srv.call('POST', '/api/partner/v1/orders', { headers: { 'X-Api-Key': key, 'Idempotency-Key': 'partner-ord-1' }, body: { quoteId: q.body.id } });
  assert.equal(o.status, 200);
  assert.equal((await srv.call('GET', '/api/partner/v1/policies', { headers: { 'X-Api-Key': key } })).body.length, 2);
  assert.equal((await srv.call('GET', '/api/partner/v1/policies', { headers: { 'X-Api-Key': other } })).body.length, 0);
  const st = await srv.call('GET', '/api/partner/v1/statement', { headers: { 'X-Api-Key': key } });
  assert.ok(st.body.totalCommission > 0);
  assert.equal((await srv.call('GET', `/api/partners/${created.body.id}/statement?from=2020-01-01`, { token: pm })).status, 200);
  const keyId = (await c.store.collection('api_keys').find({ where: { partner_id: created.body.id } }))[0].id;
  assert.equal((await srv.call('DELETE', `/api/partners/keys/${keyId}`, { token: pm })).status, 200);
  assert.equal((await srv.call('GET', '/api/partner/v1/policies', { headers: { 'X-Api-Key': key } })).status, 401);
  assert.equal((await srv.call('PATCH', `/api/partners/${created.body.id}`, { token: pm, body: { status: 'suspended' } })).body.status, 'suspended');
});

test('customer app: signed-link session, home, declare expiry, quote, pay, consent, claim, export; IDOR blocked', async () => {
  const p = await findProfile(c, (x) => x.ownerType === 'individual' && x.policy.insurer !== 'TASCO' && !x.anonymised && x.vehicle.category === 'car_under6');
  assert.equal((await srv.call('POST', '/api/customer/session', { body: { link: `${p.id}.forged` } })).status, 401);
  const link = c.links.sign(p.id);
  const sess = await srv.call('POST', '/api/customer/session', { body: { link } });
  const t = sess.body.token;
  assert.equal((await srv.call('GET', '/api/leads', { token: t })).status, 403, 'customer token cannot call staff APIs');
  const home = await srv.call('GET', '/api/customer/home', { token: t });
  assert.equal(home.body.vehicle.plate, p.plate);
  assert.equal((await srv.call('POST', '/api/customer/expiry', { token: t, body: { expiryDate: '2026-12-01', insurer: 'PTI' } })).status, 200);
  const q = await srv.call('POST', '/api/customer/quotes', { token: t, body: { products: [{ code: 'TNDS_CAR' }] } });
  const otherCustomer = await findProfile(c, (x) => x.id !== p.id && !x.anonymised);
  const t2 = (await srv.call('POST', '/api/customer/session', { body: { demoProfileId: otherCustomer.id } })).body.token;
  assert.equal((await srv.call('POST', '/api/customer/orders', { token: t2, body: { quoteId: q.body.id }, headers: { 'Idempotency-Key': 'cust-idor-1' } })).status, 404, 'IDOR blocked');
  const o = await srv.call('POST', '/api/customer/orders', { token: t, body: { quoteId: q.body.id }, headers: { 'Idempotency-Key': 'cust-pay-001' } });
  assert.equal(o.status, 200);
  assert.equal((await srv.call('PUT', '/api/customer/consent', { token: t, body: { call: false } })).body.consent.call, false);
  const cl = await srv.call('POST', '/api/customer/claims', { token: t, body: { policyId: o.body.policies[0].certNo, incidentDate: o.body.policies[0].startDate, description: 'minor scratch' } });
  assert.equal(cl.status, 200);
  assert.equal((await srv.call('GET', '/api/customer/claims', { token: t })).body.length, 1);
  assert.equal((await srv.call('GET', '/api/customer/data-export', { token: t })).body.profile.id, p.id);
  const ch = await srv.login('claims');
  assert.equal((await srv.call('GET', '/api/claims', { token: ch })).body.length >= 1, true);
  assert.equal((await srv.call('PATCH', `/api/claims/${cl.body.id}`, { token: ch, body: { status: 'acknowledged' } })).body.status, 'acknowledged');
});

test('data steward, compliance (DSAR), auditor, admin and support endpoints', async () => {
  const steward = await srv.login('steward');
  const issues = await srv.call('GET', '/api/dq/issues?status=open&limit=3', { token: steward });
  assert.ok(issues.body.total > 0);
  assert.equal((await srv.call('POST', `/api/dq/issues/${encodeURIComponent(issues.body.items[0].id)}/resolve`, { token: steward, body: { resolution: 'verified' } })).status, 200);
  assert.equal((await srv.call('POST', '/api/dq/issues/nope/resolve', { token: steward, body: { resolution: 'x' } })).status, 404);
  const p = await findProfile(c, (x) => !x.anonymised);
  assert.equal((await srv.call('PATCH', `/api/customers/${p.id}/expiry`, { token: steward, body: { expiryDate: '2027-02-02', evidence: 'certificate photo' } })).status, 200);
  assert.equal((await srv.call('PATCH', '/api/customers/NOPE/expiry', { token: steward, body: { expiryDate: '2027-02-02', evidence: 'x' } })).status, 404);
  const ing = await srv.call('POST', '/api/data/ingest', { token: steward, body: { source: 'partner_bank', records: [{ recordId: 'API-1', plateRaw: '99A-123.45', phoneRaw: '0987000111', fullName: 'Bùi An', hack: 'ignored' }] } });
  assert.equal(ing.body.records, 1);
  assert.equal((await srv.call('POST', '/api/data/ingest', { token: steward, body: { source: 'x', records: [{ plateRaw: '1' }] } })).status, 400);
  const dpo = await srv.login('compliance');
  const target = await findProfile(c, (x) => !x.anonymised && x.policy.insurer !== 'TASCO');
  assert.equal((await srv.call('POST', `/api/dsar/${target.id}/export`, { token: dpo })).status, 200);
  const er = await srv.call('POST', `/api/dsar/${target.id}/erase`, { token: dpo });
  assert.ok([200, 422].includes(er.status));
  const auditor = await srv.login('auditor');
  assert.equal((await srv.call('GET', `/api/audit?entityId=${target.id}`, { token: auditor })).status, 200);
  assert.equal((await srv.call('POST', '/api/rules', { token: auditor, body: { kind: 'x', payload: {} } })).status, 403);
  const admin = await srv.login('admin');
  assert.ok((await srv.call('GET', '/api/users', { token: admin })).body.length >= 14);
  const nu = await srv.call('POST', '/api/users', { token: admin, body: { username: 'api.user', password: 'long enough pw!', displayName: 'API', roles: ['executive'] } });
  assert.equal(nu.status, 200);
  assert.equal((await srv.call('PATCH', `/api/users/${nu.body.user.id}`, { token: admin, body: { region: 'Hà Nội' } })).body.region, 'Hà Nội');
  assert.equal((await srv.call('GET', `/api/customers/${p.id}`, { token: admin })).status, 403, 'admin has no customer data access (SoD)');
  const support = await srv.login('support');
  const st = await srv.call('GET', '/api/ops/status', { token: support });
  assert.equal(st.body.store, 'memory');
  assert.ok(st.body.integrations.every((i) => i.circuit === 'closed'));
  for (const k of ['reconciliation', 'retention', 'relay']) assert.equal((await srv.call('POST', `/api/ops/jobs/${k}`, { token: support })).status, 200, k);
  assert.equal((await srv.call('POST', '/api/ops/jobs/nope', { token: support })).status, 404);
  assert.ok((await srv.call('GET', '/api/ops/jobs', { token: support })).body.length >= 3);
  const pw = await srv.call('POST', '/api/auth/password', { token: support, body: { currentPassword: 'Tasco@Demo2026!', newPassword: 'Another long password' } });
  assert.equal(pw.status, 200);
});
