'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const { makeContainer, ACTOR, findProfile } = require('../helpers');
const { totp } = require('../../src/shared/crypto');

let c;
test.before(async () => { c = await makeContainer(); });

test('rules: maker-checker lifecycle with validation, four-eyes and rollback', async () => {
  const author = ACTOR('author-1', ['rule_author']);
  const approver = ACTOR('approver-1', ['rule_approver']);
  const scoring = await c.services.rules.get('scoring');
  const changed = structuredClone(scoring);
  changed.tiers.hot = 65;
  await assert.rejects(c.services.rules.createDraft({ kind: 'scoring', payload: { ...changed, tiers: { hot: 1, warm: 2 } } }, author), /invalid/);
  const draft = await c.services.rules.createDraft({ kind: 'scoring', payload: changed, description: 'lower hot threshold' }, author);
  assert.equal(draft.version_no, 2);
  await assert.rejects(c.services.rules.approve(draft.id, approver), /Only pending/);
  await assert.rejects(c.services.rules.submit(draft.id, approver), /Only the author/);
  await c.services.rules.submit(draft.id, author);
  await assert.rejects(c.services.rules.submit(draft.id, author), /Only drafts/);
  await assert.rejects(c.services.rules.approve(draft.id, author), /Maker-checker/);
  await assert.rejects(c.services.rules.reject(draft.id, author), /Maker-checker/);
  await c.services.rules.approve(draft.id, approver, { comment: 'ok' });
  assert.equal((await c.services.rules.get('scoring')).tiers.hot, 65);
  const v1 = await c.services.rules.byId('scoring@1');
  assert.equal(v1.status, 'retired');
  const rb = await c.services.rules.rollback('scoring@1', author);
  assert.equal(rb.status, 'draft');
  await c.services.rules.submit(rb.id, author);
  await c.services.rules.reject(rb.id, approver, { comment: 'not now' });
  assert.equal((await c.services.rules.byId(rb.id)).status, 'rejected');
  await assert.rejects(c.services.rules.reject(rb.id, approver), /Only pending/);
  const msgs = structuredClone(await c.services.rules.get('content.messages'));
  msgs.templates.first_reminder.vi = 'Giảm giá 20% khi gia hạn!';
  await assert.rejects(c.services.rules.createDraft({ kind: 'content.messages', payload: msgs }, author), (e) => e.details.some((d) => d.includes('copy guard')));
  assert.ok((await c.services.rules.list({ kind: 'scoring' })).length === 3);
  assert.ok((await c.services.rules.snapshot()).some((s) => s.kind === 'scoring' && s.version === 2));
  assert.deepEqual(await c.services.rules.validate('scoring', scoring), []);
  await assert.rejects(c.services.rules.byId('nope@1'), /not found/);
  await assert.rejects(c.services.rules.get('nope'), /not found/);
  const actions = (await c.services.audit.list({ limit: 200 })).map((a) => a.action);
  for (const a of ['rules.draft_created', 'rules.submitted', 'rules.approved', 'rules.rejected']) assert.ok(actions.includes(a), a);
});

test('identity: login, MFA, lockout, password change, user admin', async () => {
  const r = await c.services.identity.login({ username: 'campaign', password: 'Tasco@Demo2026!' }, { ip: '1.1.1.1' });
  assert.ok(r.accessToken);
  assert.ok(r.user.permissions.includes('journeys:run'));
  const principal = await c.services.identity.authenticate(r.accessToken);
  assert.equal(principal.username, 'campaign');
  c.services.identity.logout(principal.claims);
  assert.equal(await c.services.identity.authenticate(r.accessToken), null, 'revoked token rejected');
  const mfa = await c.services.identity.login({ username: 'approver', password: 'Tasco@Demo2026!' });
  assert.equal(mfa.mfaRequired, true);
  await assert.rejects(c.services.identity.verifyMfa({ mfaToken: mfa.mfaToken, code: '000000' }), /Invalid code/);
  await assert.rejects(c.services.identity.verifyMfa({ mfaToken: 'bad', code: '123456' }), /expired/);
  const secret = await c.services.identity.getTotpSecretForDemo('approver');
  const ok = await c.services.identity.verifyMfa({ mfaToken: mfa.mfaToken, code: totp(secret) });
  assert.ok(ok.accessToken);
  await assert.rejects(c.services.identity.login({ username: 'nobody', password: 'x' }), /Invalid username or password/);
  for (let i = 0; i < 5; i++) await assert.rejects(c.services.identity.login({ username: 'exec', password: 'wrong' }));
  await assert.rejects(c.services.identity.login({ username: 'exec', password: 'Tasco@Demo2026!' }), /locked/);
  const admin = ACTOR('admin-x', ['admin']);
  await assert.rejects(c.services.identity.createUser({ username: 'weak', password: 'short', displayName: 'W', roles: ['executive'] }, admin), /Password policy/);
  await assert.rejects(c.services.identity.createUser({ username: 'x', password: 'long enough pw', displayName: 'X', roles: ['god'] }, admin), /Unknown role/);
  const created = await c.services.identity.createUser({ username: 'new.agent', password: 'long enough pw', displayName: 'N', roles: ['telesales_agent'], region: 'Hà Nội' }, admin);
  await assert.rejects(c.services.identity.createUser({ username: 'new.agent', password: 'long enough pw', displayName: 'N', roles: ['telesales_agent'] }, admin), /exists/);
  const upd = await c.services.identity.update(created.user.id, { status: 'disabled' }, admin);
  assert.equal(upd.status, 'disabled');
  await assert.rejects(c.services.identity.login({ username: 'new.agent', password: 'long enough pw' }), /Invalid/);
  await assert.rejects(c.services.identity.update('nope', {}, admin), /not found/);
  await assert.rejects(c.services.identity.update(created.user.id, { roles: ['god'] }, admin), /Unknown role/);
  const me = (await c.services.identity.list()).find((u) => u.username === 'admin');
  await assert.rejects(c.services.identity.update(me.id, { roles: ['executive'] }, { ...admin, id: me.id }), /own admin role/);
  const camp = (await c.services.identity.list()).find((u) => u.username === 'campaign');
  await c.services.identity.changePassword(camp.id, { currentPassword: 'Tasco@Demo2026!', newPassword: 'A much longer pass 1' });
  await assert.rejects(c.services.identity.changePassword(camp.id, { currentPassword: 'wrong', newPassword: 'whatever long' }), /incorrect/);
  await assert.rejects(c.services.identity.changePassword(camp.id, { currentPassword: 'A much longer pass 1', newPassword: 'short' }), /Password policy/);
  assert.equal(await c.services.identity.authenticate('garbage'), null);
});

test('MFA is enforced for privileged roles even if not enrolled', async () => {
  const admin = ACTOR('admin-y', ['admin']);
  await c.services.identity.createUser({ username: 'steward2', password: 'long enough pw', displayName: 'S', roles: ['data_steward'], enableMfa: false }, admin);
  await assert.rejects(c.services.identity.login({ username: 'steward2', password: 'long enough pw' }), /MFA enrolment required/);
});

test('access policy: RBAC deny-by-default, ABAC region and assignment, PII masking', async () => {
  const { access } = c.services;
  const agent = { id: 'u-agent', roles: ['telesales_agent'], region: 'Hà Nội' };
  const camp = { id: 'u-camp', roles: ['campaign_manager'], region: 'ALL' };
  assert.throws(() => access.require(null, 'leads:read'), /Authentication required/);
  assert.throws(() => access.require(camp, 'users:manage'), /Missing permission/);
  access.require(agent, 'handoff:work');
  await access.check(agent, 'read', { type: 'profile', region: 'Hà Nội' });
  await assert.rejects(access.check(agent, 'read', { type: 'profile', region: 'Đà Nẵng' }), /regional_data/);
  await assert.rejects(access.check(agent, 'update', { type: 'handoff', assignedTo: 'someone-else' }), /agent_own_handoffs/);
  await access.check(agent, 'update', { type: 'handoff', assignedTo: null, region: 'Hà Nội' });
  await assert.rejects(access.check(agent, 'read', { type: 'handoff', assignedTo: null, region: 'Đà Nẵng' }), /agent_own_handoffs/);
  await access.check(camp, 'read', { type: 'profile', region: 'Đà Nẵng' });
  const masked = access.maskProfile(camp, { name: 'Nguyễn Văn An', phone: '0912345678', altPhones: ['0987654321'] });
  assert.equal(masked.phone, '0912***678');
  assert.equal(masked.piiMasked, true);
  assert.equal(access.maskProfile(agent, { phone: '0912345678' }).phone, '0912345678');
  assert.equal(access.maskProfile(agent, null), null);
  await access.check({ id: 'customer:X', roles: ['customer'], customerId: 'X' }, 'read', { type: 'customer_self', ownerId: 'X' });
  await assert.rejects(access.check({ id: 'customer:X', roles: ['customer'], customerId: 'X' }, 'read', { type: 'customer_self', ownerId: 'Y' }));
});

test('voice service: console session, campaign calls, outcomes feed data and telesales', async () => {
  const camp = ACTOR('camp', ['campaign_manager']);
  const p = await findProfile(c, (x) => x.consent.call && !x.consent.dnc && x.phone && x.policy.expiryConfidence >= 0.5 && x.ownerType === 'individual');
  const s = await c.services.voice.start(p.id, camp);
  const plateSpoken = p.plate.replace('-', ' ').replace('.', ' ');
  await c.services.voice.turn(s.id, plateSpoken, camp);
  await c.services.voice.turn(s.id, 'đúng', camp);
  const done = await c.services.voice.turn(s.id, 'tôi muốn mua ngay', camp);
  assert.equal(done.outcome, 'hot_handoff');
  assert.ok(done.handoffId);
  await assert.rejects(c.services.voice.turn(s.id, 'more', camp), /already ended/);
  await assert.rejects(c.services.voice.turn('nope', 'x', camp), /not found/);
  await assert.rejects(c.services.voice.get('nope'), /not found/);
  const h = await c.services.voice.getHandoff(done.handoffId);
  const agent = ACTOR('agent-z', ['telesales_agent']);
  const claimed = await c.services.voice.updateHandoff(h.id, { status: 'claimed', note: 'calling now' }, agent);
  assert.equal(claimed.assignedTo, 'agent-z');
  await assert.rejects(c.services.voice.updateHandoff(h.id, { status: 'open', version: 1 }, agent), /modified by someone else/);
  const won = await c.services.voice.updateHandoff(h.id, { status: 'won' }, agent);
  assert.equal(won.status, 'won');
  await assert.rejects(c.services.voice.updateHandoff(h.id, { status: 'claimed' }, agent), /Cannot move/);
  assert.ok((await c.services.voice.listHandoffs({ status: 'won', assignedTo: 'agent-z', region: p.province })).total >= 1);
  const opt = await findProfile(c, (x) => x.id !== p.id && x.consent.call && !x.consent.dnc && x.phone);
  const s2 = await c.services.voice.start(opt.id, camp);
  await c.services.voice.turn(s2.id, 'đừng gọi nữa', camp);
  await c.events.drain();
  const after = await c.store.collection('profiles').get(opt.id);
  assert.equal(after.consent.dnc, true, 'opt-out recorded');
  await assert.rejects(c.services.voice.start(opt.id, camp), /do-not-contact/);
  const outcomes = {};
  const hot = await c.services.leads.list({ tier: 'warm', limit: 40 });
  for (const l of hot.items.slice(0, 25)) { const r = await c.services.voice.autoCall(l.id); outcomes[r.outcome] = (outcomes[r.outcome] || 0) + 1; }
  await c.events.drain();
  assert.ok(Object.keys(outcomes).length >= 3, JSON.stringify(outcomes));
  const gov = await c.services.insights.governance();
  assert.ok(gov.voiceBot.calls >= 25);
  assert.equal(gov.auditChain.ok, true);
});

test('customer self-service: home, declare expiry, consent, claims FNOL, DSAR export/erase', async () => {
  const p = await findProfile(c, (x) => x.ownerType === 'individual' && x.vehicle.category === 'car_under6' && x.policy.insurer !== 'TASCO' && !x.anonymised);
  const me = { id: `customer:${p.id}`, roles: ['customer'], customerId: p.id };
  const home = await c.services.customers.home(p.id);
  assert.equal(home.vehicle.plate, p.plate);
  await c.services.customers.declareExpiry(p.id, { expiryDate: '2026-11-15', insurer: 'PVI' }, me);
  await c.events.drain();
  assert.equal((await c.store.collection('profiles').get(p.id)).policy.expiryMethod, 'customer_declared');
  await c.services.customers.updateConsent(p.id, { marketing: false }, me);
  await c.services.ingestion.rebuild([p.id], 'test');
  assert.equal((await c.store.collection('profiles').get(p.id)).consent.marketing, false, 'consent survives rebuilds');
  const q = await c.services.sales.quote({ profileId: p.id, products: [{ code: 'TNDS_CAR' }], channel: 'vetc_app' }, me);
  const { policies } = await c.services.sales.purchase({ quoteId: q.id, idempotencyKey: 'cust-0001' }, me);
  await c.events.drain();
  const pol = policies[0];
  await assert.rejects(c.services.claims.submit({ profileId: p.id, policyId: pol.id, incidentDate: '2020-01-01', description: 'x' }, me), /outside the policy period/);
  await assert.rejects(c.services.claims.submit({ profileId: 'OTHER', policyId: pol.id, incidentDate: pol.startDate, description: 'x' }, me), /not found/);
  const claim = await c.services.claims.submit({ profileId: p.id, policyId: pol.id, incidentDate: pol.startDate, description: 'rear-ended', location: 'km 35' }, me);
  const handler = ACTOR('claims', ['claims_handler']);
  await c.services.claims.transition(claim.id, 'acknowledged', handler);
  await assert.rejects(c.services.claims.transition(claim.id, 'paid', handler), /Cannot move/);
  assert.equal((await c.services.claims.list({ profileId: p.id })).length, 1);
  await assert.rejects(c.services.claims.get('nope'), /not found/);
  const exp = await c.services.customers.exportData(p.id, me);
  assert.equal(exp.profile.id, p.id);
  assert.ok(exp.sourceRecords.every((r) => !r._hidden));
  await assert.rejects(c.services.customers.erase(p.id, me), /Active policy in force/);
  const other = await findProfile(c, (x) => x.id !== p.id && !x.anonymised && x.name);
  await c.services.customers.erase(other.id, ACTOR('dpo', ['compliance_officer']));
  const erased = await c.store.collection('profiles').get(other.id);
  assert.equal(erased.name, null);
  assert.equal(erased.anonymised, true);
  await assert.rejects(c.services.customers.home(other.id), /not found/);
  await c.services.ingestion.rebuild([other.id], 'test');
  assert.equal((await c.store.collection('profiles').get(other.id)).anonymised, true, 'erasure survives rebuilds');
  assert.match(c.services.customers.issueCustomerToken(p.id), /^ey/);
});

test('ops: retention, DQ resolution, lineage, jobs, adoption KPIs', async () => {
  const ret = await c.services.ops.applyRetention('test');
  assert.ok(ret.runId);
  const dq = await c.services.ops.dqIssues({ limit: 5 });
  assert.ok(dq.total > 0);
  const resolved = await c.services.ops.resolveDq(dq.items[0].id, { resolution: 'fixed' }, ACTOR('steward', ['data_steward']));
  assert.equal(resolved.status, 'resolved');
  assert.equal(await c.services.ops.resolveDq('nope', { resolution: 'x' }, ACTOR()), null);
  const p = await findProfile(c, () => true);
  const lin = await c.services.ops.lineage(p.id);
  assert.ok(lin.fields.length > 0);
  assert.ok((await c.services.ops.jobRuns()).length >= 1);
  await assert.rejects(c.services.ops.recordRun('boom', 'test', async () => { throw new Error('x'); }), /x/);
  const adoption = await c.services.insights.adoption();
  assert.ok(adoption.logins >= 1);
  assert.ok(adoption.targets.avgClicksToRenew);
});
